<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="mecanum_with_rollers" params="name type radius width flip pos_x pos_y pos_z mass">
    <link name="${name}_mecanum_link">
      <xacro:inertial_cylinder mass="${mass}" length="${width}" radius="${radius}">
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      </xacro:inertial_cylinder>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://robot_description/meshes/mec_hub_${type}.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="silver"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_mecanum_joint" type="continuous">
      <origin xyz="${pos_x} ${pos_y} ${pos_z}" rpy="0 ${flip} 0"/>
      <parent link="chassis_link"/>
      <child link="${name}_mecanum_link"/>
      <axis xyz="0.0 0.0 ${copysign(1, (flip * -1))}"/>
    </joint>

    <xacro:roller name="${name}" number="0" wheel_radius="${radius}"/>
    <xacro:roller name="${name}" number="1" wheel_radius="${radius}"/>
    <xacro:roller name="${name}" number="2" wheel_radius="${radius}"/>
    <xacro:roller name="${name}" number="3" wheel_radius="${radius}"/>
    <xacro:roller name="${name}" number="4" wheel_radius="${radius}"/>
    <xacro:roller name="${name}" number="5" wheel_radius="${radius}"/>
    <xacro:roller name="${name}" number="6" wheel_radius="${radius}"/>
    <xacro:roller name="${name}" number="7" wheel_radius="${radius}"/>
    <xacro:roller name="${name}" number="8" wheel_radius="${radius}"/>
  </xacro:macro>

  <xacro:property name="roller_middle_radius" value="${0.0194/2}" />
  <xacro:property name="roller_second_radius" value="${0.01904/2}" />
  <xacro:property name="roller_third_radius" value="${0.01797/2}" />
  <xacro:property name="roller_cylinder_radius" value="0.0074" />
  <xacro:property name="roller_length" value="0.0396" />
  <xacro:macro name="roller" params="name number wheel_radius">
    <!-- Type Negative: When 1 output 1. When 2 output -1 -->
    <xacro:property name="type_negative" value="${(type * 2 - 3) * -1}" />
    <xacro:property name="roller_total" value="9" />
    <xacro:property name="roller_radians" value="${2 * pi / roller_total * number}" />
    <xacro:property name="roller_x_pos" value="${sin(roller_radians) * wheel_radius}" />
    <xacro:property name="roller_y_pos" value="${cos(roller_radians) * wheel_radius}" />
    <xacro:property name="roller_x_rot" value="${sin(roller_radians) * (pi/4) * type_negative}" />
    <xacro:property name="roller_y_rot" value="${cos(roller_radians) * (pi/4) * type_negative}" />
    <xacro:property name="roller_z_rot" value="${tan(roller_radians) * (pi/4) * type_negative}" />

    <link name="${name}_roller_${number}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://robot_description/meshes/roller.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="silver"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${roller_middle_radius}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 ${roller_length/5}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${roller_second_radius}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -${roller_length/5}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${roller_second_radius}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 ${2 * roller_length/5}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${roller_third_radius}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -${2 * roller_length/5}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${roller_third_radius}"/>
        </geometry>
      </collision>
    </link>
    

    <joint name="${name}_roller_${number}_joint" type="continuous">
      <origin xyz="${roller_x_pos} ${roller_y_pos} 0" rpy="${roller_x_rot} ${roller_y_rot} 0"/>
      <parent link="${name}_mecanum_link"/>
      <child link="${name}_roller_${number}"/>
      <axis xyz="0.0 0.0 1.0"/>
    </joint>
  </xacro:macro>
</robot>
