<?xml version="1.0" ?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find robot_description)/urdf/materials.xacro" />
<xacro:include filename="$(find robot_description)/urdf/macros.xacro" />
<xacro:include filename="$(find robot_description)/urdf/robot.trans" />
<xacro:include filename="$(find robot_description)/urdf/robot.gazebo" />

<!-- Properties -->

<xacro:property name="chassis_length" value="0.18" />
<xacro:property name="chassis_width" value="0.33" />
<xacro:property name="chassis_height" value="0.135" />
<xacro:property name="chassis_weight" value="2.45" />

<xacro:property name="wheel_radius" value="0.0466" />
<xacro:property name="wheel_thickness" value="0.042" />
<xacro:property name="wheel_weight" value=".136" />

<xacro:property name="joint_pos_x" value="0.09" />
<xacro:property name="joint_pos_y" value="0.145" />
<xacro:property name="joint_pos_z" value="0.121" />

<!-- Links -->

<link name="chassis">
  <xacro:inertial_box mass="${chassis_weight}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
    <origin xyz="0 0 -${chassis_height / 2}" rpy="0 0 0"/>
  </xacro:inertial_box>
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://robot_description/meshes/chassis.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="0 0 -${chassis_height / 2}" rpy="0 0 0"/>
    <geometry>
      <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
    </geometry>
  </collision>
</link>


<link name="wheel_front_right">
  <xacro:inertial_cylinder mass="${wheel_weight}" length="${wheel_thickness}" radius="${wheel_radius}">
    <origin xyz="${wheel_thickness/2} 0 0" rpy="0 ${pi/2} 0"/>
  </xacro:inertial_cylinder>
  <visual>
    <origin xyz="0 0 0" rpy="0 ${pi} 0"/>
    <geometry>
      <mesh filename="package://robot_description/meshes/wheel_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="${wheel_thickness/2} 0 0" rpy="0 ${pi/2} 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
  </collision>
</link>


<link name="wheel_front_left">
  <xacro:inertial_cylinder mass="${wheel_weight}" length="${wheel_thickness}" radius="${wheel_radius}">
    <origin xyz="-${wheel_thickness/2} 0 0" rpy="0 ${pi/2} 0"/>
  </xacro:inertial_cylinder>
  <visual>
    <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
    <geometry>
      <mesh filename="package://robot_description/meshes/wheel_2.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="-${wheel_thickness/2} 0 0" rpy="0 ${pi/2} 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
  </collision>
</link>


<link name="wheel_rear_right">
  <xacro:inertial_cylinder mass="${wheel_weight}" length="${wheel_thickness}" radius="${wheel_radius}">
    <origin xyz="${wheel_thickness/2} 0 0" rpy="0 ${pi/2} 0"/>
  </xacro:inertial_cylinder>
  <visual>
    <origin xyz="0 0 0" rpy="0 -${pi/2} 0"/>
    <geometry>
      <mesh filename="package://robot_description/meshes/wheel_2.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="${wheel_thickness/2} 0 0" rpy="0 ${pi/2} 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
  </collision>
</link>


<link name="wheel_rear_left">
  <xacro:inertial_cylinder mass="${wheel_weight}" length="${wheel_thickness}" radius="${wheel_radius}">
    <origin xyz="-${wheel_thickness/2} 0 0" rpy="0 ${pi/2} 0"/>
  </xacro:inertial_cylinder>
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://robot_description/meshes/wheel_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <origin xyz="-${wheel_thickness/2} 0 0" rpy="0 ${pi/2} 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
  </collision>
</link>


<joint name="wheel_FR_joint" type="continuous">
  <origin xyz="${joint_pos_x} ${joint_pos_y} -${joint_pos_z}" rpy="0 0 0"/>
  <parent link="chassis"/>
  <child link="wheel_front_right"/>
  <axis xyz="1.0 0.0 0.0"/>
</joint>


<joint name="wheel_FL_joint" type="continuous">
  <origin xyz="-${joint_pos_x} ${joint_pos_y} -${joint_pos_z}" rpy="0 0 0"/>
  <parent link="chassis"/>
  <child link="wheel_front_left"/>
  <axis xyz="1.0 0.0 0.0"/>
</joint>


<joint name="wheel_RR_joint" type="continuous">
  <origin xyz="${joint_pos_x} -${joint_pos_y} -${joint_pos_z}" rpy="0 0 0"/>
  <parent link="chassis"/>
  <child link="wheel_rear_right"/>
  <axis xyz="1.0 0.0 0.0"/>
</joint>


<joint name="wheel_RL_joint" type="continuous">
  <origin xyz="-${joint_pos_x} -${joint_pos_y} -${joint_pos_z}" rpy="0 0 0"/>
  <parent link="chassis"/>
  <child link="wheel_rear_left"/>
  <axis xyz="1.0 0.0 0.0"/>
</joint>


</robot>
