controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_train_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters:
    extra_joints: [
      "rear_right_roller_0_joint",
      "rear_right_roller_1_joint",
      "rear_right_roller_2_joint",
      "rear_right_roller_3_joint",
      "rear_right_roller_4_joint",
      "rear_right_roller_5_joint",
      "rear_right_roller_6_joint",
      "rear_right_roller_7_joint",
      "rear_right_roller_8_joint",
      "rear_left_roller_0_joint",
      "rear_left_roller_1_joint",
      "rear_left_roller_2_joint",
      "rear_left_roller_3_joint",
      "rear_left_roller_4_joint",
      "rear_left_roller_5_joint",
      "rear_left_roller_6_joint",
      "rear_left_roller_7_joint",
      "rear_left_roller_8_joint",
      "front_left_roller_0_joint",
      "front_left_roller_1_joint",
      "front_left_roller_2_joint",
      "front_left_roller_3_joint",
      "front_left_roller_4_joint",
      "front_left_roller_5_joint",
      "front_left_roller_6_joint",
      "front_left_roller_7_joint",
      "front_left_roller_8_joint",
      "front_right_roller_0_joint",
      "front_right_roller_1_joint",
      "front_right_roller_2_joint",
      "front_right_roller_3_joint",
      "front_right_roller_4_joint",
      "front_right_roller_5_joint",
      "front_right_roller_6_joint",
      "front_right_roller_7_joint",
      "front_right_roller_8_joint"]

diff_drive_train_controller:
  ros__parameters:
    left_wheel_names: ["front_left_mecanum_joint", "rear_left_mecanum_joint"]
    right_wheel_names: ["front_right_mecanum_joint", "rear_right_mecanum_joint"]

    wheel_separation: 0.18
    wheels_per_side: 2  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.0466

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 10.0
    angular.z.min_velocity: -10.0
    angular.z.max_acceleration: 10.0
    angular.z.min_acceleration: -10.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0